# Generated by Django 5.0 on 2023-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JWData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('TradeCode', models.CharField(max_length=50)),
                ('High', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Volume', models.IntegerField()),
            ],
        ),
    ]
